# Give your finance database a name
spring.datasource.url=jdbc:h2:mem:financetransactions
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Let Hibernate automatically build your SQL tables based on Transaction.java
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update

# Keep the H2 Console enabled so you can view raw database tables in your browser
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
server.port=8081